# -*- coding: utf-8 -*-
"""2548562_DL_Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXqoxlNZEvTQ13ViUPQMYX5hzMQbVbNe

# Building CNN from scratch

## Setup
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist

"""## Load Dataset"""

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# normalize
x_train = x_train / 255.0
x_test = x_test / 255.0

# reshape to (samples, channels, height, width)
x_train = x_train.reshape(-1,1,28,28)
x_test = x_test.reshape(-1,1,28,28)

"""## Implementing Convolution Layer"""

def conv_forward(image, filt, bias, stride=1):
    # extracting filter dimensions
    n_filters, n_c, f, _ = filt.shape
    # extracting image dimensions
    n_c, in_dim, _ = image.shape

    # calculating output dimension according to image and filter
    out_dim = int((in_dim - f)/stride) + 1

    # initializing output feature maps
    out = np.zeros((n_filters, out_dim, out_dim))


    # loop through each filter
    for curr_f in range(n_filters):
        curr_y = out_y = 0
        # this for moving filter vertically
        while curr_y + f <= in_dim:
            curr_x = out_x = 0
            # this for moving filter horizontally
            while curr_x + f <= in_dim:
                # the convolution operation
                out[curr_f, out_y, out_x] = np.sum(
                    filt[curr_f] * image[:, curr_y:curr_y+f, curr_x:curr_x+f]
                ) + bias[curr_f]
                # move filter position to right
                curr_x += stride
                out_x += 1
            # this for moving filter position to down
            curr_y += stride
            out_y += 1
    # returns extracted features
    return out

"""- this function will apply convolution filters to an input image to extract features
- it takes image, filt(kernel), bias (added after convolution) and stride (step size of filter movement) as input
- Extracting filter dimensions: n_filters is number of filters, n_c is channer (for RGB there are 3 and for our grayscale, there is only one), and f is the filter size.
- Extracting image dimensions: n_c is again channel, and in_dim is height and width
- applies multiple filters across the input image to extract important visual features
- Each filter slides across the image and computes element-wise multiplication followed by summation and bias addition
- This process generates feature maps that highlight patterns such as edges and curves, enabling the CNN to learn meaningful representations from the input

## ReLU function
"""

def relu(x):
    return np.maximum(0, x)

"""## Max Pooling"""

# function takes image, size of pooling window and
# stride of pooling window as input
def maxpool(image, size=2, stride=2):
    # getting dimension of the feature mape (we get it from conv_forward functoin)
    # channer, height, weight
    n_c, h_prev, w_prev = image.shape

    # calculates the heights and weights after max pooling
    h = int((h_prev - size)/stride) + 1
    w = int((w_prev - size)/stride) + 1

    # initializing output with zeroes
    downsampled = np.zeros((n_c, h, w))

    # looping through each feature map
    for i in range(n_c):
        curr_y = out_y = 0
        # while loop to move window veritcally
        while curr_y + size <= h_prev:
            curr_x = out_x = 0
            # while loop to move window horizontally
            while curr_x + size <= w_prev:
                # select maximum value from the window
                downsampled[i, out_y, out_x] = np.max(
                    image[i, curr_y:curr_y+size, curr_x:curr_x+size]
                )
                # move window to right
                curr_x += stride
                out_x += 1
            # move window to left
            curr_y += stride
            out_y += 1
    return downsampled

"""- Max pooling performs downsampling by selecting the maximum value from small regions of the feature map that we will get from the conv_forward funtion
- it helps reduce computation, reduce overfitting, retain strongest features and make model robust to small shifts.
- we take max value because we want to extract strongest edge, strongest curve or most important feature

## Softmax and Loss
"""

def softmax(x):
    e = np.exp(x - np.max(x))
    return e / e.sum()

def cross_entropy(pred, label):
    return -np.log(pred[label])

"""- softmax converts raw output scores into probabilities
- we subtract by np.max(x) to prevent numerical overflow when exponent value become very large
- cross_entropy measures how wrong the prediction is
- if predicted probability is too far from true probability, it will assing bigger loss
- otherewise, it will assign a smaller loss

## Fully Connected layer
"""

# takes flattened features as input and gives output
def dense(x, W, b):
    return np.dot(W, x) + b

"""## Pipeline"""

np.random.seed(0)

# 8 filters of 3x3 size
# dividing by 9 keeps values small and maintains stable learning
filt = np.random.randn(8,1,3,3) / 9
# to shift activation values
bias = np.zeros((8,1))

# 10 weights for 10 output classes
W = np.random.randn(10, 1352) * 0.01
# 10 biase
b = np.zeros((10,1))

"""## Forward Pass Example"""

# process 10 first images
for i in range(10):
  # input image
  img = x_train[i]
  # label
  label = y_train[i]

  # convolution layer
  conv = conv_forward(img, filt, bias)

  # relu activation function to remove negative values
  relu_out = relu(conv)

  # max pooling
  pool = maxpool(relu_out)

  # falttening the output
  fc_input = pool.flatten().reshape(-1,1)

  # sending it to dense layer
  out = dense(fc_input, W, b)

  # softmax activation function to count probabilities
  probs = softmax(out)

  print("Predicted:", np.argmax(probs))
  print("Actual:", label)

"""# YOLO

## YOLO V8

### Setup
"""

!pwd

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/DL datasets"

!ls

!pip install ultralytics -q

# download dataset
!wget -q https://github.com/ultralytics/assets/releases/download/v0.0.0/signature.zip

# unzip dataset
!unzip -q signature.zip

!ls

!unzip -q signature.zip

!ls signature

!ls

!ls signature/images/train | head

"""### YOLOv8 Training"""

data = "/content/drive/MyDrive/DL datasets/signature.yaml"

"""- the above yaml file has information about dataset structure, including training and validation images paths and class labels"""

from ultralytics import YOLO

# loading pre-trained YOLO model
model_v8 = YOLO('yolov8n.pt')

# training the model on signature dataset
model_v8.train(
    data=data,
    epochs=50,
    # resizing image to 640x640 for better standarization
    imgsz=640,
    batch=8,
    project="/content/drive/MyDrive/DL datasets",
    name='signature_training_v8'
)

"""- The YOLOv8 model was trained for 50 epochs using 640 x 640 images.

### Model Inference
"""

from ultralytics import YOLO

model_v8 = YOLO("/content/drive/MyDrive/DL datasets/signature_training_v8/weights/best.pt")

model_v8.predict(
    source="/content/drive/MyDrive/DL datasets/signature/images/val",
    save=True,
    save_txt=True,
    save_conf=True
)

model_v8.predict(
    source="/content/drive/MyDrive/DL datasets/signature/images/val",
    save=True,
    # if confidence is < 0.25 then it will be removed
    conf=0.25
)

"""#### Now we can see the output in runs/detect/predict

### Validation and Visualization
"""

from ultralytics import YOLO

model_v8 = YOLO("/content/drive/MyDrive/DL datasets/signature_training_v8/weights/best.pt")

metrics_v8 = model_v8.val()
metrics_v8

"""- The trained YOLO v8 model was evaluated on 35 validation images
- model achieved a precision of 0.997 and recall of 1.0
- we can tell that it is highly accurate detection with no missed signatures
- The mAP@0.5 score of 0.995 also demonstrates excellent detection performance
- the mAP@0.5-0.95 score of 0.969 indicates strong bounding box localizatoin acccuracy
"""

from IPython.display import Image
Image(filename="/content/drive/MyDrive/DL datasets/signature_training_v8/results.png")

"""- The training and validation loss curves show a steady decrease
- the model successfully learned meaningful features without overfitting
- Precision and recall rapidly improved and stabilized near 1.0, demonstrating reliable detection performance
- The mAP curves show continuous improvement, reaching values close to 1.0
"""

from IPython.display import Image, display
import glob

results = glob.glob("/content/drive/MyDrive/DL datasets/runs/detect/predict/*.jpg")

for img in results[:5]:
    display(Image(filename=img))

"""## YOLO v5

### Setup
"""

!pwd

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
!pip install -r requirements.txt

"""
### Training the model"""

# Commented out IPython magic to ensure Python compatibility.
import os

# Ensure the current directory is where yolov5 is cloned
# %cd /content/drive/MyDrive/DL datasets/yolov5

# Construct the command with quoted paths
!python train.py \
  --img 640 \
  --batch 8 \
  --epochs 50 \
  --data "/content/drive/MyDrive/DL datasets/signature.yaml" \
  --weights yolov5s.pt \
  --project signature_training_v5 \
  --name yolov5

!pwd

"""### validation and visualization"""

!python val.py \
  --weights signature_training_v5/yolov54/weights/best.pt \
  --data "/content/drive/MyDrive/DL datasets/signature.yaml" \
  --img 640

"""- the model was validated using 35 images, it shows the precision of 0.99 and recall of 1 just like before in YOLO v8.
- it learned patterns meaningfully, and scores demonstrates that
"""

!python detect.py \
  --weights signature_training_v5/yolov54/weights/best.pt \
  --source "/content/drive/MyDrive/DL datasets/yolov5/signature/images/val" \
  --conf 0.25 \
  --save-txt \
  --save-conf

from IPython.display import Image
Image(filename='/content/drive/MyDrive/DL datasets/yolov5/signature_training_v5/yolov54/results.png')

from IPython.display import Image, display
import glob

v5_results = glob.glob("/content/drive/MyDrive/DL datasets/yolov5/runs/detect/exp/*.jpg")

for img in v5_results[:5]:
    display(Image(filename=img))

"""# Ensemble implementation

## Setup
"""

import os
import glob

v5_labels_path = "/content/drive/MyDrive/DL datasets/yolov5/runs/detect/exp/labels"
v8_labels_path = "/content/drive/MyDrive/DL datasets/runs/detect/predict/labels"

# folder to save ensemble predictions
ensemble_output = "/content/drive/MyDrive/DL datasets/ensemble_labels"
os.makedirs(ensemble_output, exist_ok=True)

"""## Generating labels using ensemble learning"""

# Convert YOLO format to box corners
# YOLO format: class x_center y_center width height confidence
def yolo_to_corners(box):
    _, x, y, w, h, conf = box
    x1 = x - w/2
    y1 = y - h/2
    x2 = x + w/2
    y2 = y + h/2
    return [x1, y1, x2, y2, conf]

# Intersection over Union (IoU)
# measures overlap between two boxes
def iou(boxA, boxB):
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])

    interArea = max(0, xB - xA) * max(0, yB - yA)

    boxAArea = (boxA[2]-boxA[0]) * (boxA[3]-boxA[1])
    boxBArea = (boxB[2]-boxB[0]) * (boxB[3]-boxB[1])

    union = boxAArea + boxBArea - interArea

    return interArea / union if union != 0 else 0



# Read YOLO label file
def read_labels(path):
    boxes = []
    if not os.path.exists(path):
        return boxes

    with open(path, "r") as f:
        for line in f.readlines():
            parts = list(map(float, line.strip().split()))
            boxes.append(parts)
    return boxes


# Ensemble process for each image
label_files = glob.glob(v5_labels_path + "/*.txt")

for file in label_files:
    filename = os.path.basename(file)

    v5_file = os.path.join(v5_labels_path, filename)
    v8_file = os.path.join(v8_labels_path, filename)

    v5_boxes = read_labels(v5_file)
    v8_boxes = read_labels(v8_file)

    combined = v5_boxes + v8_boxes

    final_boxes = []

    # Remove duplicate boxes using IoU
    while combined:
        chosen = combined.pop(0)
        chosen_corner = yolo_to_corners(chosen)

        keep = True

        for fb in final_boxes:
            fb_corner = yolo_to_corners(fb)

            # if boxes overlap heavily then duplicate
            if iou(chosen_corner, fb_corner) > 0.5:
                # keep box with higher confidence
                if chosen[5] > fb[5]:
                    final_boxes.remove(fb)
                    final_boxes.append(chosen)
                keep = False
                break
        if keep:
            final_boxes.append(chosen)

    # Save ensemble results
    out_path = os.path.join(ensemble_output, filename)

    with open(out_path, "w") as f:
        for box in final_boxes:
            f.write(" ".join(map(str, box)) + "\n")

print("Ensemble predictions saved to:", ensemble_output)

"""## Generating output images"""

import cv2
import os
import glob
from matplotlib import pyplot as plt

# Paths
image_folder = "/content/drive/MyDrive/DL datasets/signature/images/val"
label_folder = "/content/drive/MyDrive/DL datasets/ensemble_labels"
output_folder = "/content/drive/MyDrive/DL datasets/ensemble_visuals"

os.makedirs(output_folder, exist_ok=True)


# Function to draw bounding boxes
def draw_boxes(image_path, label_path):
    img = cv2.imread(image_path)
    h, w, _ = img.shape

    if os.path.exists(label_path):
        with open(label_path, "r") as f:
            for line in f.readlines():
                cls, x, y, bw, bh, conf = map(float, line.split())

                # Convert YOLO format → pixel coordinates
                x1 = int((x - bw/2) * w)
                y1 = int((y - bh/2) * h)
                x2 = int((x + bw/2) * w)
                y2 = int((y + bh/2) * h)

                # Draw rectangle
                cv2.rectangle(img, (x1, y1), (x2, y2), (0,255,0), 2)

                # Label text
                label = f"Signature {conf:.2f}"
                cv2.putText(img, label, (x1, y1-5),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.5, (0,255,0), 1)

    return img

# Draw ensemble detections
image_paths = glob.glob(image_folder + "/*.jpg")

for img_path in image_paths[:5]:  # show first 5 images
    filename = os.path.basename(img_path)
    label_path = os.path.join(label_folder, filename.replace(".jpg",".txt"))
    result_img = draw_boxes(img_path, label_path)

    # Save output
    save_path = os.path.join(output_folder, filename)
    cv2.imwrite(save_path, result_img)

    # VVisualization
    plt.figure(figsize=(6,6))
    plt.imshow(cv2.cvtColor(result_img, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.title("Ensemble Detection Result")
    plt.show()

print("✅ Ensemble visual results saved in:", output_folder)

"""## Comparison and visualization"""

import cv2
import os
import glob
from matplotlib import pyplot as plt


# paths
image_folder = "/content/drive/MyDrive/DL datasets/signature/images/val"
v5_labels = "/content/drive/MyDrive/DL datasets/yolov5/runs/detect/exp/labels"
v8_labels = "/content/drive/MyDrive/DL datasets/runs/detect/predict/labels"
ens_labels = "/content/drive/MyDrive/DL datasets/ensemble_labels"



# Function to draw bounding boxes
def draw_boxes(image_path, label_path, color):
    img = cv2.imread(image_path)
    h, w, _ = img.shape

    if os.path.exists(label_path):
        with open(label_path, "r") as f:
            for line in f.readlines():
                parts = list(map(float, line.split()))
                cls, x, y, bw, bh, conf = parts

                x1 = int((x - bw/2) * w)
                y1 = int((y - bh/2) * h)
                x2 = int((x + bw/2) * w)
                y2 = int((y + bh/2) * h)

                cv2.rectangle(img, (x1, y1), (x2, y2), color, 2)
                cv2.putText(img, f"{conf:.2f}", (x1, y1-5),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 1)
    return img



# Compare detections
image_paths = glob.glob(image_folder + "/*.jpg")

for img_path in image_paths[:5]:   # show 5 samples
    filename = os.path.basename(img_path)

    v5_path = os.path.join(v5_labels, filename.replace(".jpg",".txt"))
    v8_path = os.path.join(v8_labels, filename.replace(".jpg",".txt"))
    ens_path = os.path.join(ens_labels, filename.replace(".jpg",".txt"))

    img_v5 = draw_boxes(img_path, v5_path, (255,0,0))   # Blue
    img_v8 = draw_boxes(img_path, v8_path, (0,0,255))   # Red
    img_ens = draw_boxes(img_path, ens_path, (0,255,0)) # Green

    plt.figure(figsize=(15,5))

    plt.subplot(1,3,1)
    plt.imshow(cv2.cvtColor(img_v5, cv2.COLOR_BGR2RGB))
    plt.title("YOLOv5")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(cv2.cvtColor(img_v8, cv2.COLOR_BGR2RGB))
    plt.title("YOLOv8")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(cv2.cvtColor(img_ens, cv2.COLOR_BGR2RGB))
    plt.title("Ensemble")
    plt.axis("off")

    plt.show()

"""- As we can see, ensemble learning does not improve results much
- because the two models that we used for ensemble learning, were already powerful enought with good precision and recall
- ensemble learning is helpful when we have more than one weak models, in this scenerio, it won't benefit us.
"""